### ISSUE TITLE
Use different colour scale configurations for historical vs future climate 

### ISSUE THREAD

**Issue by rod-glover** [pacificclimate/dash-dv-explorer#93]
Also we could take the opportunity to refactor the config more nicely in a couple of other minor ways.

This suggests a `dvs.xxx` config item approximately like:

```yaml
description: xxx
historical:
    units: xxx
    datasets:
        stations:
            path: xxx
            column: xxx
        model: xxx
        reconstruction: xxx
        table_C2: xxx
    colour_map: xxx
    scale:
        default: xxx
future:
    units: xxx
    datasets:
        "0.5": xxx
        "1.0": xxx
        "1.5": xxx
        # etc.
    colour_map: xxx
    scale:
        default: xxx
```
